canonical/snapd-glib

snapd-glib/snapd-glib.h
The <snapd-glib/snapd-enum-types.h> header has guards to prevent it being included outside of <snapd-glib/snapd-glib.h>.  However, that header doesn't actually include it for you.
=> Make <snapd-glib/snapd-glib.h> include snapd-enum-types.h

snapd-qt/Makefile.am
Don't define "signals", otherwise we had the following error:
/usr/include/glib-2.0/gio/gdbusintrospection.h:155:25: error: expected member name or ';' after declaration specifiers
GDBusSignalInfo     **signals;
~~~~~~~~~~~~~~~       ^
/usr/include/QtCore/qobjectdefs.h:94:22: note: expanded from macro 'signals'
=> Fix snapd-qt build

configure.ac
json-glib 1.2 is not available on Ubuntu 16.04 (xenial) but 1.1.2 is. A build
with 1.1.2 goes fine so lets use that as new baseline.
=> configure: json-glib 1.1 is enough to build

snapd-glib/snapd-client.c, snapd-glib/snapd-client.h, snapd-qt/Snapd/client.h, snapd-qt/client.cpp, tests/mock-snapd.c, tests/mock-snapd.h, tests/test-glib.c, tests/test-qt.cpp
This branch is intended to complement https://github.com/snapcore/snapd/pull/3795 by adding `set_allow_interaction` and `get_allow_interaction` APIs to `SnapdClient`.  The idea is to let the client decide whether snapd's polkit authorisation checks should allow interaction or not.
One question is what the default should be for snapd-glib.  At present I've set it to default to allow interaction on the assumption that most users of the library will be graphical.  But it would be pretty easy to disallow interaction by default.
The change should be backward compatible with old versions of snapd: they will simply ignore the extra request header.
=> Add API to control whether polkit authorisation checks allow interaction

snapd-glib/snapd-client.c
This was found whilst using the Python GIR bindings and deliberately
causing the snapd.socket service to fail (i.e. emulation of a missing
snapd service at runtime). During process exit and finalisation of the
SnapdClient object, the socket would be unconditionally closed regardless
of whether connection had succeeded or not.
This commit adds a very trivial guard around the cleanup.
Signed-off-by: Ikey Doherty <ikey@solus-project.com>
=> Fix runtime assertion when snapd socket is NULL

snapd-glib/snapd-json.c
If JSON error response doesn't include a "kind" field, fall back on the HTTP response status code.
=> snapd-glib: Use response status code to set error codes as a backup.

tests/mock-snapd.c
I was noticing some instability in the test suite when working on another change, and did a bit of refactoring of the MockSnapd code to see if it improved matters.  Unfortunately it seems I was in the middle of some work you were doing on master, so some of this might not be appropriate any more.  I thought I'd submit the PR all the same.
The main changes in this branch are:
1. directly use SoupServer rather than reimplementing an HTTP server
2. push some of the initialisation and clean up to the worker thread, so quitting the worker thread's main loop cleans things up.
=> tests: port MockSnapd to SoupServer

snapd-glib/snapd-client.c
Currently snapd-glib explicitly omits the authorisation details when calling the `/v2/login` API.  This PR removes that special case behaviour.
When a client receives an unauthorised call, there are two possible causes:
1. the client has called a snapd API that requires admin permissions without a valid snapd macaroon.
2. the client provided a valid snapd macaroon to snapd, but snapd could not use the corresponding store macaroon to call a store API.
The current behaviour is fine for use case (1), but for use case (2) it would be better to associate updated store credentials with the existing snapd macaroon rather than throwing it out completely.  This can be achieved by calling `/v2/login` with our existing snapd credentials.  This will associate the new store macaroon with the existing …
=> snapd-glib: also send auth data for /v2/login requests

snapd-qt/Snapd/channel.h
Otherwise we get a warning from QML every time it's accessed that it may change.
=> Qt: Mark constant properties as such

snapd-glib/snapd-client.c, tests/test-glib.c
Properly reset socket_path to the default if NULL is passed to
snapd_client_set_socket_path. Also add unit test.
=> client: Fix snapd_client_set_socket_path

snapd-glib/requests/snapd-json.c, tests/mock-snapd.c, tests/test-glib.c, tests/test-qt.cpp
snapd hasn't populated these since 2.40 and instead puts in a note that is
confusing snapd-glib into thinking there is one screenshot.
snapd-glib will now always return 0 screenshots.
=> Remove screenshot decoding code

snapd-glib/snapd-enum-types.c.in, snapd-glib/snapd-enum-types.h.in
Whilst working on the [Reproducible Builds](https://reproducible-builds.org/) effort we noticed that snapd-glib could not be built reproducibly. This is because it embedded the full build path in comments.
This was originally filed in Debian as [#952694](https://bugs.debian.org/952694).
=> Make the build reproducible

snapd-glib/snapd-client-sync.c, snapd-glib/snapd-client.c
The previous annotations would cause Python to crash, due to it freeing the
elements on the hash table (which are freed by the hash table itself).
Fixes https://github.com/snapcore/snapd-glib/issues/88
=> Fix annotations for SnapdClient.get_snap_conf

.github/workflows/test.yaml
travis-ci.org has a banner saying it will be shut down in a few weeks, and that projects would be migrated to travis-ci.com.  It seems there is no longer an Open Source plan with the .com service, and the project would be switched to a trial plan that would eventually run out of minutes.
As an alternative, this PR ports the CI over to using Github Actions.  I've done a a mostly direct conversion of the Travis build script, only taking advantage of GH Actions built-in docker container syntax, and the conditional syntax for enabling container specific set up.
A sample run of the workflow can be seen here:
https://github.com/jhenstridge/snapd-glib/actions/runs/550765880
=> ci: enble Github Actions based CI, using Travis script as a base

snapd-glib/requests/snapd-get-aliases.c, snapd-glib/requests/snapd-get-apps.c, snapd-glib/requests/snapd-get-assertions.c, snapd-glib/requests/snapd-get-buy-ready.c, snapd-glib/requests/snapd-get-change.c, snapd-glib/requests/snapd-get-changes.c, snapd-glib/requests/snapd-get-connections.c, snapd-glib/requests/snapd-get-find.c, snapd-glib/requests/snapd-get-icon.c, snapd-glib/requests/snapd-get-interfaces-legacy.c, snapd-glib/requests/snapd-get-interfaces.c, snapd-glib/requests/snapd-get-sections.c, snapd-glib/requests/snapd-get-snap-conf.c, snapd-glib/requests/snapd-get-snap.c, snapd-glib/requests/snapd-get-snaps.c, snapd-glib/requests/snapd-get-system-info.c, snapd-glib/requests/snapd-get-users.c, snapd-glib/requests/snapd-json.c, snapd-glib/requests/snapd-json.h, snapd-glib/requests/snapd-post-assertions.c, snapd-glib/requests/snapd-post-buy.c, snapd-glib/requests/snapd-post-change.c, snapd-glib/requests/snapd-post-create-user.c, snapd-glib/requests/snapd-post-create-users.c, snapd-glib/requests/snapd-post-login.c, snapd-glib/requests/snapd-post-logout.c, snapd-glib/requests/snapd-post-snapctl.c, snapd-glib/requests/snapd-request-async.c
This PR modifies the _snapd_json_parse_response` utility function to add a `JsonNode **error_value` out parameter that will be set to the `value` property of error responses it decodes.
The eventual goal is to update the `snapd_client_run_snapctl*` functions to correctly support non-zero exit codes, which are returned by snapd as error responses with the exit code, and command output stored in the error value.  I've submitted this PR on its own since it touches every request handler class, and didn't want to mix in a largely mechanical changes with ones that deserve more scrutiny.
=> snapd-glib: add error_value out parameter to _snapd_json_parse_response

.github/workflows/test.yaml
Add an extra step to the CI to collect the meson log files if the job fails.  Each job has a unique artifact name so that logs from different matrix runs don't overwrite each other.
=> ci: collect Meson's log files on failed builds

snapd-glib/requests/snapd-json.c
Need to support the older version for now, but can remove once we depend on glib >= 2.68
=> Handle deprecated g_time_zone_new

snapd-glib/requests/snapd-get-change.c, snapd-glib/requests/snapd-get-change.h, snapd-glib/requests/snapd-post-change.c, snapd-glib/requests/snapd-post-change.h, snapd-glib/requests/snapd-post-themes.c, snapd-glib/requests/snapd-request-async.c, snapd-glib/requests/snapd-request-async.h, snapd-glib/snapd-client.c, tests/mock-snapd.c
This PR is intended to help fix https://github.com/snapcore/snapd-desktop-integration/issues/7, together with https://github.com/snapcore/snapd/pull/11450 on the snapd side. The snapd side has been merged and cherry-picked into the 2.55 branch.
The themes status API was intended to be usable from the restricted REST API available over `/run/snapd-snap.socket` to snaps that plug snap-themes-control. While the main requests function, we didn't expose a way to track the status of async tasks such as the one created by `snapd_client_install_themes_*`.
Rather than exposing the entire changes interface, a subset of it is available at `/v2/accessories/changes/NNN`, and will only provide details of changes initated through the themes interface.
This snapd-glib change makes SnapdRequestAsync …
=> snapd-glib: use /v2/accessories/changes endpoint to check status of themes requests

snapd-glib/requests/snapd-get-apps.c, snapd-glib/requests/snapd-get-assertions.c, snapd-glib/requests/snapd-get-changes.c, snapd-glib/requests/snapd-get-find.c, snapd-glib/requests/snapd-get-icon.c, snapd-glib/requests/snapd-get-snap-conf.c, snapd-glib/requests/snapd-get-snap.c, snapd-glib/requests/snapd-get-themes.c, snapd-glib/requests/snapd-post-snap.c, snapd-glib/requests/snapd-put-snap-conf.c
This method is removed in libsoup3, and is unnecessary as there is an equivalent in GLib.
=> Replace soup_uri_encode with g_string_append_uri_escaped

snapd-qt/meson.build
Otherwise compilation of Discover with snap back-end fails with:
```
FAILED: libdiscover/backends/SnapBackend/libsnapclient/CMakeFiles/libsnap_helper.dir/SnapAuthHelper.cpp.o
/usr/bin/x86_64-pc-linux-gnu-g++ -DKCOREADDONS_LIB -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_FROM_BYTEARRAY -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_NO_FOREACH -DQT_NO_KEYWORDS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_SIGNALS_SLOTS_KEYWORDS -DQT_NO_URL_CAST_FROM_STRING -DQT_STRICT_ITERATORS -DQT_USE_QSTRINGBUILDER -DTRANSLATION_DOMAIN=\"libdiscover\" -D_GNU_SOURCE -D_LARGEFILE64_SOURCE -I/tmp/portage/kde-plasma/discover-6.0.4-r1/work/discover-6.0.4_build/libdiscover/backends/SnapBackend/libsnapclient -I/tmp/portage/kde-plasma/discover-6.0.4-r1/work/discover-6.0.4/libdisco …
```
=> snapd-qt/meson.build: Install Notice header

snapd-glib/meson.build, snapd-glib/requests/snapd-json.c, snapd-glib/snapd-task-data.c, snapd-glib/snapd-task-data.h, snapd-glib/snapd-task.c, snapd-glib/snapd-task.h, snapd-qt/Snapd/TaskData, snapd-qt/Snapd/task-data.h, snapd-qt/Snapd/task.h, snapd-qt/meson.build, snapd-qt/task-data.cpp, snapd-qt/task.cpp, tests/mock-snapd.c, tests/mock-snapd.h, tests/test-glib.c, tests/test-qt.cpp
This "data" field can contain several info, like the list of snaps that are affected by this task. Implemented in https://github.com/snapcore/snapd/pull/13953
=> Added support for data field in SnapdTask

snapd-glib/requests/snapd-json.c
The property is an int, so this might break on systems where sizeof(gint32) != sizeof(int) and may be the cause for https://bugs.launchpad.net/ubuntu/+source/snapd-glib/+bug/2077200
=> Don't use gint32 for nanoseconds.

.github/workflows/test.yaml
The tests in Bionic fail due to a problem in nodejs. Found a workaround at the end of https://github.com/actions/checkout/issues/1590 It consists on disable using node20 and allow using an insecure version of nodejs.
Fix #168
=> Fix test for 18.04

snapd-glib/snapd-notice.c, snapd-glib/snapd-notice.h, snapd-glib/snapd-notices-monitor.c, snapd-qt/notice.cpp, tests/test-glib.c
Several getters were returning a reference of the data instead of just a pointer; this is, they incremented the refcount of the returned element. This isn't what the rest of the API does, so for uniformity, this PR adds new versions of the getters and deprecates the old ones.
Fix #170
=> Fix notices2 getters

snapd-glib/requests/snapd-get-notices.c, snapd-glib/requests/snapd-json.c
At least in ARMhf systems, the current code fails due to the difference in sizes for long int and long long int. This patch fixes it.
Fix https://github.com/canonical/snapd-glib/issues/162
=> Fix build in 32bit systems

.github/workflows/documentation.yaml, doc/reference/meson.build
It seems that gi-docgen is still experimental, so I decided to maintain gtk-doc and just create a workflow to generate the HTML and upload it to the pages of snapd-glib.
=> Generate documentation on push to master

.github/workflows/documentation.yaml
It seems that it is required to have the last version.
=> Update deploy action to last version

snapd-glib/snapd-notices-monitor.c
When creating the new snapd_notice_get... calls and deprecating the old ones, this one was left for replacement.
=> Don't use deprecated calls

.clang-format, snapd-glib/snapd-client-sync.c, snapd-glib/snapd-client.c
The autoformatting has the problem of cutting comments in several lines, which is a problem for the GIR parser if a GIR line with parentheses is cut and the opening and closing parentheses are in different lines.
This change instructs clang-format to not reflow comments. It also fixes the GIR errors.
=> Fix GIR comments

tests/mock-snapd.c, tests/test-glib.c
The snapd mock had some leaks. These patches fix them, to allow to find future leaks more easily.
=> Fix memory leaks in mock

snapd-glib/requests/snapd-get-notices.c, tests/mock-snapd.c, tests/mock-snapd.h, tests/test-glib.c
The mock-snapd class allows to simulate receiving notices, but until now it didn't honor the "after" field, so it always returned all the notices.
This patch changes this, also allowing to test that the "after" parameter is correctly parsed. This, also, allowed to find a bug when requesting notices after a specific date when using GLib 2.65 or previous.
=> Added test support for "after"

snapd-glib/snapd-notice.c, snapd-glib/snapd-notice.h
The snapd_notice_get_notice_type() method returns a notice type, which is an `enum`. But the return type is defined as `const`, which causes a warning in the compiler when using the option `-Wignored-qualifiers`.
This patch removes the unneeded `const` qualifier to remove this warning.
Fix https://github.com/canonical/snapd-glib/issues/200
=> Fix warning

.github/workflows/test.yaml
The checkout@v3 action relies on node20, which requires a version of GLibc newer than the one distributed in Ubuntu 18.04. Until now we used a workaround to be able to still run the action and, thus, execute the tests, but that workaround ceased to work and now neither the current code, nor any new PR do pass the continuous integration tests in github.
Since Ubuntu 18.04 reached end-of-life in May 2023, it makes sense to remove support.
=> Remove support for Ubuntu 18.04

meson.build, snapd-glib/snapd-version.h
After setting the 1.67 tag, it's required to update the version value to 1.68 in meson.build.
=> Update version number

meson.build, snapd-glib/snapd-version.h
Since version 1.68 has been tagged, this PR changes all the version definitions to 1.69, to make the code ready for the next release.
=> Update definitions to version 1.69

meson.build, snapd-glib/snapd-version.h
Since version 1.69 has been tagged, this PR changes all the version definitions to 1.70, to make the code ready for the next release.
=> Update definitions to version 1.70

snapd-qt/Snapd/link.h
It's not possible to use Q_DECL_EXPORT due to Arch compiling with no_direct_extern_access (https://github.com/canonical/snapd-glib/issues/175 ) so our own macro LIBSNAPDQT_EXPORT must be used.
This patch fixes it.
=> Fix build in ARCH

.github/workflows/check_q_decl_export.yaml, .github/workflows/documentation.yaml, .github/workflows/format.yaml, .github/workflows/test.yaml
Currently, the default branch is `master`, but we are renaming all of them to the current default name `main`. Unfortunately, the CI tests expects the default branch to be `master`.
This patch changes this to support both branches, thus allowing the renaming at any moment.
=> ci: Allow to rename the default branch to `main`
